"""
GraphQL queries for RateMyProfessor API
"""

# Import all queries from the existing queries file
from helpful_files_and_docs.graphql_queries.rmp_queries import (
    # Teacher queries
    NEWSEARCHTEACHERS_QUERY,
    TEACHERRATINGSPAGE_QUERY,
    RATINGSLIST_QUERY,
    RATETEACHER_QUERY,
    RATETEACHEREDIT_QUERY,
    TEACHERSEARCHPAGINATION_QUERY,
    TEACHERSEARCHRESULTSPAGE_QUERY,
    # School queries
    NEWSEARCHSCHOOLS_QUERY,
    SCHOOLRATINGSPAGE_QUERY,
    SCHOOLRATINGSLIST_QUERY,
    SCHOOLSEARCHPAGINATION_QUERY,
    SCHOOLSEARCHRESULTSPAGE_QUERY,
    # Rating queries
    RATINGPAGE_QUERY,
    # User queries
    MYRATINGSLIST_QUERY,
    SAVEDPROFESSORSLIST_QUERY,
    USERACCOUNTSETTINGSPAGE_QUERY,
    # Utility queries
    GLOBALCONTEXTPROVIDER_QUERY,
    OAUTHBUTTONURL_QUERY,
)

__all__ = [
    # Teacher queries
    "NEWSEARCHTEACHERS_QUERY",
    "TEACHERRATINGSPAGE_QUERY",
    "RATINGSLIST_QUERY",
    "RATETEACHER_QUERY",
    "RATETEACHEREDIT_QUERY",
    "TEACHERSEARCHPAGINATION_QUERY",
    "TEACHERSEARCHRESULTSPAGE_QUERY",
    # School queries
    "NEWSEARCHSCHOOLS_QUERY",
    "SCHOOLRATINGSPAGE_QUERY",
    "SCHOOLRATINGSLIST_QUERY",
    "SCHOOLSEARCHPAGINATION_QUERY",
    "SCHOOLSEARCHRESULTSPAGE_QUERY",
    # Rating queries
    "RATINGPAGE_QUERY",
    # User queries
    "MYRATINGSLIST_QUERY",
    "SAVEDPROFESSORSLIST_QUERY",
    "USERACCOUNTSETTINGSPAGE_QUERY",
    # Utility queries
    "GLOBALCONTEXTPROVIDER_QUERY",
    "OAUTHBUTTONURL_QUERY",
]
